workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    environment:
      xcode: latest
      node: 18
      vars:
        BUNDLE_ID: "app.lovable.b08ea0c4542c4ad687821586e398e8dd"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.lovable.b08ea0c4542c4ad687821586e398e8dd
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web assets
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
